name: Resnet18_CIFAR10
project: ampere_acc_test
entity: tejalapeno
program: train/train.py

method: grid

parameters:
  model:
    value: Resnet18
  epochs:
    value: 50
  dataset:
    value: CIFAR10
  batch_size:
    values: [64, 128, 256]
  learning_rate:
    value: .001
  val_ratio:
    value: .2
